<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="ani" />

<meta name="date" content="2015-01-15" />

<title>R Script for Chapter 6</title>

<script src="Chapter06_files/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="Chapter06_files/bootstrap-3.3.1/css/readable.min.css" rel="stylesheet" />
<script src="Chapter06_files/bootstrap-3.3.1/js/bootstrap.min.js"></script>
<script src="Chapter06_files/bootstrap-3.3.1/shim/html5shiv.min.js"></script>
<script src="Chapter06_files/bootstrap-3.3.1/shim/respond.min.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>



</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img { 
  max-width:100%; 
  height: auto; 
}
</style>
<div class="container-fluid main-container">


<div id="header">
<h1 class="title">R Script for Chapter 6</h1>
<h4 class="author"><em>ani</em></h4>
<h4 class="date"><em>January 15, 2015</em></h4>
</div>

<div id="TOC">
<ul>
<li><a href="#generating-null-distributions-of-proportions-and-testing-the-handedness-of-toads"><span class="toc-section-number">1</span> - Generating Null Distributions of Proportions and Testing the Handedness of Toads</a></li>
<li><a href="#what-if-h_0-is-not-rejected"><span class="toc-section-number">2</span> - What if <span class="math inline">\(H_0\)</span> is Not Rejected?</a></li>
<li><a href="#one-sided-tests"><span class="toc-section-number">3</span> - One-Sided Tests</a></li>
<li><a href="#some-worked-examples"><span class="toc-section-number">4</span> - Some Worked Examples</a><ul>
<li><a href="#problem-11"><span class="toc-section-number">4.1</span> - Problem 11</a></li>
<li><a href="#problem-14"><span class="toc-section-number">4.2</span> - Problem 14</a></li>
</ul></li>
</ul>
</div>

<div id="generating-null-distributions-of-proportions-and-testing-the-handedness-of-toads" class="section level1">
<h1><span class="header-section-number">1</span> - Generating Null Distributions of Proportions and Testing the Handedness of Toads</h1>
<p>We will begin with the toad example.The series of commands below will accomplish the following. We first create a sample size of 10 million observations (here toads). We then use the <code>rbinom()</code> command to generate binomial probabilities of observing, in this sample, 0, 1, 2, 3, …, 17, 18 right-handed toads, under the assumption that right-handed toads occur with probability = 0.5. We then construct a frequency table that we call <code>tab.x</code>, and then a relative frequency table that we have named <code>proptab.x</code>. The last command plots these relative frequencies.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">10000000</span>
x &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">18</span>, <span class="dt">p=</span><span class="fl">0.5</span>)
tab.x &lt;-<span class="st"> </span><span class="kw">table</span>(x)
<span class="kw">data.frame</span>(tab.x)</code></pre></div>
<pre><code>##     x    Freq
## 1   0      47
## 2   1     713
## 3   2    5817
## 4   3   31301
## 5   4  116881
## 6   5  327035
## 7   6  707358
## 8   7 1216675
## 9   8 1668030
## 10  9 1854476
## 11 10 1667703
## 12 11 1213769
## 13 12  708562
## 14 13  326785
## 15 14  116805
## 16 15   31424
## 17 16    5868
## 18 17     705
## 19 18      46</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">proptab.x &lt;-<span class="st"> </span>(<span class="kw">table</span>(x)/n)
<span class="kw">data.frame</span>(proptab.x)</code></pre></div>
<pre><code>##     x      Freq
## 1   0 0.0000047
## 2   1 0.0000713
## 3   2 0.0005817
## 4   3 0.0031301
## 5   4 0.0116881
## 6   5 0.0327035
## 7   6 0.0707358
## 8   7 0.1216675
## 9   8 0.1668030
## 10  9 0.1854476
## 11 10 0.1667703
## 12 11 0.1213769
## 13 12 0.0708562
## 14 13 0.0326785
## 15 14 0.0116805
## 16 15 0.0031424
## 17 16 0.0005868
## 18 17 0.0000705
## 19 18 0.0000046</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(proptab.x, <span class="dt">ylab=</span><span class="st">&quot;Probability&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;No. of Right-Handed Toads&quot;</span>, <span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">18</span>), <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.25</span>), <span class="dt">col=</span><span class="st">&quot;lightblue&quot;</span>) </code></pre></div>
<p><img src="Chapter06_files/figure-html/1-1.png" /><!-- --></p>
<p>Notice that the plot peaks at 9 right-handed toads because that is what we said with the <code>p=0.5</code> switch – half the toads sampled should be right-handed.</p>
<p>Now, assume we sampled 18 toads and exactly 14 turned out to be right-handed. This means in our sample we have <code>14/18</code> right-handed toads. This could happen by chance of course but if the TRUE distribution is an equal chance of right-handed and left-handed toads then we should have ended up with only 9 right-handed toads.</p>
<p>So we set about asking: What would be the probability of getting 14 or more toads if in the population right-handed toads occur with <span class="math inline">\(p=0.5\)</span>? We could calculate this from <code>proptab.x</code> as <span class="math inline">\(0.0116489 + 0.0031092 + ... + 0.0000052\)</span> but this would be inefficient. Instead, the code below will do this very calculation for us.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(proptab.x[<span class="dv">15</span>:<span class="dv">19</span>])</code></pre></div>
<pre><code>## [1] 0.0154848</code></pre>
<p>Because we have a two-tailed test we would have to allow for seeing 4 or fewer right-handed toads. Given the symmetry of the distribution this means doubling up the sum we arrived at above. That is, the probability of seeing either 14 or more right-handed toads or 4 or fewer right-handed toads if <span class="math inline">\(H_0\)</span> were true is <code>2 * sum(proptab.x[15:19])</code></p>
<p>Had we decided <strong>before conducting the test</strong> to Reject <span class="math inline">\(H_0\)</span> if the <span class="math inline">\(P-value\)</span> were <span class="math inline">\(\leq 0.05\)</span> then we would have to reject the belief that right-handed and left-handed toads occur with equal frequency in the population. Why this decision? Because <code>0.0309696</code> is less than <span class="math inline">\(0.05\)</span></p>
<p>What if we had decided to Reject <span class="math inline">\(H_0\)</span> if the <span class="math inline">\(P-value\)</span> were <span class="math inline">\(\leq 0.01\)</span>? Why then we would be unable to reject the belief that right-handed and left-handed toads occur with equal frequency in the population.</p>
</div>
<div id="what-if-h_0-is-not-rejected" class="section level1">
<h1><span class="header-section-number">2</span> - What if <span class="math inline">\(H_0\)</span> is Not Rejected?</h1>
<p>Here we take up the case of a situation when <span class="math inline">\(H_0\)</span> is not rejected, and we do so with data on mud plantains wherein left- and right-handed individuals are believe to occur in a 1:3 ratio. A sample of 27 mud plantains from a particular crossing (see Example 6.4 on page 161) yielded 6 left-handed flowers. Do these data support the belief that the crossing should yield left- and right-handed flowers in a 1:3 ratio? We start by setting forth the hypotheses and our decision rule.</p>
<p><span class="math inline">\(H_0: \text{ Left-handed and right-handed offspring occur with a 1:3 ratio } (p=0.25)\)</span><br />
<span class="math inline">\(H_A: \text{ Left-handed and right-handed offspring do not occur with a 1:3 ratio } (p \neq 0.25)\)</span></p>
<p>Let us decide to Reject <span class="math inline">\(H_0\)</span> if the <span class="math inline">\(P-value \leq 0.05\)</span></p>
<p>Let us generate the distribution to be expected if <span class="math inline">\(H_0\)</span> were true (called the Null distribution).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">10000000</span>
x &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">27</span>, <span class="fl">0.25</span>)
tab.x &lt;-<span class="st"> </span><span class="kw">table</span>(x); tab.x</code></pre></div>
<pre><code>## x
##       0       1       2       3       4       5       6       7       8 
##    4210   37871  164818  458430  915950 1407850 1719474 1718781 1431778 
##       9      10      11      12      13      14      15      16      17 
## 1007640  605424  312024  137834   53390   17719    5122    1351     285 
##      18      19      20 
##      43       5       1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">proptab.x &lt;-<span class="st"> </span>(<span class="kw">table</span>(x)/n); proptab.x</code></pre></div>
<pre><code>## x
##         0         1         2         3         4         5         6 
## 0.0004210 0.0037871 0.0164818 0.0458430 0.0915950 0.1407850 0.1719474 
##         7         8         9        10        11        12        13 
## 0.1718781 0.1431778 0.1007640 0.0605424 0.0312024 0.0137834 0.0053390 
##        14        15        16        17        18        19        20 
## 0.0017719 0.0005122 0.0001351 0.0000285 0.0000043 0.0000005 0.0000001</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(proptab.x, <span class="dt">ylab=</span><span class="st">&quot;Probability&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;No. of Right-Handed Flowers&quot;</span>, <span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">27</span>), <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.20</span>), <span class="dt">col=</span><span class="st">&quot;lightblue&quot;</span>) </code></pre></div>
<p><img src="Chapter06_files/figure-html/3-1.png" /><!-- --></p>
<p>If <span class="math inline">\(H_0\)</span> were true we should have seen <code>0.25 * 27</code> left-handed flowers. Now, what is the probability of seeing the 6 left-handed flowers that we saw in this sample?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(proptab.x[<span class="dv">1</span>:<span class="dv">7</span>])</code></pre></div>
<pre><code>## [1] 0.4708603</code></pre>
<p>Since it is a two-sided test we would have to double this probability to get <code>0.9417206</code> and this <span class="math inline">\(P-value\)</span> is far greater than <span class="math inline">\(0.05\)</span>. Hence we fail to reject <span class="math inline">\(H_0\)</span>. That is, the sample data provide insufficient evidence to conclude that left- and right-handed flowers occur with something other than a 1:3 ratio.</p>
<p>Caution is warranted of course. Why? Because <span class="math inline">\(H_0\)</span> could still be false but somehow our sample gave us the wrong result by chance alone. Perhaps had we drawn 100 flowers at random our conclusion would have been to reject <span class="math inline">\(H_0\)</span>. As a result, whenever we fail to reject <span class="math inline">\(H_0\)</span> we will conclude that the data provide evidence that supports <span class="math inline">\(H_0\)</span>.</p>
</div>
<div id="one-sided-tests" class="section level1">
<h1><span class="header-section-number">3</span> - One-Sided Tests</h1>
<p>Assume that a study is designed to test whether daughters resemble their fathers. Participants are shown one photo of a girl and photos of two adult men, and then asked to guess which of the two men is the girl’s father. If there is no resemblance in the population then the probability of the participant selecting the actual father should at most be equal to a guess – 50:50, i.e., <span class="math inline">\(p=0.5\)</span>. If there is a resemblance then the probability of picking the actual father should be greater than 50:50 (i.e., <span class="math inline">\(p &gt; 0.5\)</span>).</p>
<p>We will begin by setting up the hypotheses and our decision rule.</p>
<p><span class="math inline">\(H_0: \text{ Participants pick the actual father correctly at most half the time } (p \leq 0.5)\)</span><br />
<span class="math inline">\(H_A: \text{ Participants pick the actual father correctly more than half the time } (p &gt; 0.5)\)</span></p>
<p>Let us decide to reject <span class="math inline">\(H_0\)</span> if the <span class="math inline">\(P-value \leq 0.05\)</span>. Now we generate the Null distribution</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">10000000</span>
x &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">18</span>, <span class="fl">0.5</span>)
tab.x &lt;-<span class="st"> </span><span class="kw">table</span>(x); tab.x</code></pre></div>
<pre><code>## x
##       0       1       2       3       4       5       6       7       8 
##      45     699    5898   31434  116486  326743  708492 1214020 1668471 
##       9      10      11      12      13      14      15      16      17 
## 1854259 1668937 1214528  708844  326203  117001   31397    5797     705 
##      18 
##      41</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">proptab.x &lt;-<span class="st"> </span>(<span class="kw">table</span>(x)/n); proptab.x</code></pre></div>
<pre><code>## x
##         0         1         2         3         4         5         6 
## 0.0000045 0.0000699 0.0005898 0.0031434 0.0116486 0.0326743 0.0708492 
##         7         8         9        10        11        12        13 
## 0.1214020 0.1668471 0.1854259 0.1668937 0.1214528 0.0708844 0.0326203 
##        14        15        16        17        18 
## 0.0117001 0.0031397 0.0005797 0.0000705 0.0000041</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(proptab.x, <span class="dt">ylab=</span><span class="st">&quot;Probability&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;No. of Correct Guesses&quot;</span>, <span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">18</span>), <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.20</span>), <span class="dt">col=</span><span class="st">&quot;cornflowerblue&quot;</span>) </code></pre></div>
<p><img src="Chapter06_files/figure-html/5-1.png" /><!-- --></p>
<p>Now assume in a sample of 18 participants some 13 successfully guessed the actual father. Does this suggest that there is a resemblance? We can start by calculating how likely it would be, if <span class="math inline">\(H_0\)</span> were true, for 13 or more participants to correctly identify the actual father.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(proptab.x[<span class="dv">14</span>:<span class="dv">19</span>])</code></pre></div>
<pre><code>## [1] 0.0481144</code></pre>
<p>This turns out to be <code>0.0481144</code> and is less than 0.05. Hence we can reject <span class="math inline">\(H_0\)</span>; the data provide sufficient evidence to conclude that daughters do indeed resemble their fathers.</p>
<p>As a rule, remember that one-sided hypothesis tests make it very easy to reject <span class="math inline">\(H_0\)</span> and hence open us up to making mistakes more often than do two-sided tests. Note also that one-sided and two-sided hypotheses and tests are also referred to as one-tailed and two-tailed hypotheses and tests.</p>
</div>
<div id="some-worked-examples" class="section level1">
<h1><span class="header-section-number">4</span> - Some Worked Examples</h1>
<div id="problem-11" class="section level2">
<h2><span class="header-section-number">4.1</span> - Problem 11</h2>
<p>Out of 18 of the largest mammal species in the Americas 16 were found to be smaller on islands than on the mainland. Do these data suggest that large mammals are likely to differ in size between islands and the mainland in a particular direction? That is, for example, that mammals will be smaller on islands? Use the conventional significance levels of <span class="math inline">\(\alpha = 0.05\)</span></p>
<p>I’ll generate the Null distribution under the following hypotheses: <span class="math inline">\(H_0: \text{ Large mammals occur as often on islands as on the mainland } (p = 0.5)\)</span><br />
<span class="math inline">\(H_A: \text{ Large mammals do not occur as often on islands as on the mainland  } (p \neq 0.5)\)</span><br />
Set <span class="math inline">\(\alpha = 0.05\)</span><br />
We know that if <span class="math inline">\(H_0\)</span> were true we should see the same proportion of larger/smaller mammals on the islands as on the mainland (i.e., <span class="math inline">\(p=0.50\)</span>). The sample proportion is: <span class="math inline">\(\hat{p}=\dfrac{16}{18} = 0.8888\)</span></p>
<p>The code below will generate, tabulate, and plot the Null distribution (i.e., when <span class="math inline">\(H_0\)</span> is true)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">10000000</span>
x &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">18</span>, <span class="fl">0.5</span>)
tab.x &lt;-<span class="st"> </span><span class="kw">table</span>(x); tab.x</code></pre></div>
<pre><code>## x
##       0       1       2       3       4       5       6       7       8 
##      31     722    5876   30909  116665  327577  707778 1214700 1667298 
##       9      10      11      12      13      14      15      16      17 
## 1855202 1669545 1214386  708030  326478  117174   31118    5740     732 
##      18 
##      39</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">proptab.x &lt;-<span class="st"> </span>(<span class="kw">table</span>(x)/n); proptab.x</code></pre></div>
<pre><code>## x
##         0         1         2         3         4         5         6 
## 0.0000031 0.0000722 0.0005876 0.0030909 0.0116665 0.0327577 0.0707778 
##         7         8         9        10        11        12        13 
## 0.1214700 0.1667298 0.1855202 0.1669545 0.1214386 0.0708030 0.0326478 
##        14        15        16        17        18 
## 0.0117174 0.0031118 0.0005740 0.0000732 0.0000039</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(proptab.x, <span class="dt">ylab=</span><span class="st">&quot;Probability&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;No. of Larger Mammals Guesses&quot;</span>, <span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">18</span>), <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="fl">0.20</span>), <span class="dt">col=</span><span class="st">&quot;cornflowerblue&quot;</span>) </code></pre></div>
<p><img src="Chapter06_files/figure-html/7-1.png" /><!-- --></p>
<p>How likely is it then that we would have seen 16 larger mammal species on the mainland? <code>{ r 8} sum(proptab.x[17:19])</code></p>
<p>Since it is a two-tailed test we will have to double this to get the <span class="math inline">\(P-value:\)</span> <code>0.0013022</code> and this tells us that the resulting <span class="math inline">\(P-value\)</span> is quite a bit less than <span class="math inline">\(\alpha = 0.05\)</span>. Hence we reject <span class="math inline">\(H_0\)</span>. The data suggest that large mammal species tend to be larger on the mainland than on islands.</p>
</div>
<div id="problem-14" class="section level2">
<h2><span class="header-section-number">4.2</span> - Problem 14</h2>
<p><span class="math inline">\(H_0: \text{ Subjects pick the mother at most half the time } (p \leq 0.5)\)</span><br />
<span class="math inline">\(H_A: \text{ Subjects pick the mother more than half the time } (p &gt; 0.5)\)</span><br />
Let <span class="math inline">\(\alpha = 0.05\)</span></p>
<p>This is a one-tailed test.</p>
<p>The test statistic would be the proportion of correct picks seen in the sample.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n &lt;-<span class="st"> </span><span class="dv">10000000</span>
x &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">18</span>, <span class="fl">0.5</span>)
tab.x &lt;-<span class="st"> </span><span class="kw">table</span>(x); tab.x</code></pre></div>
<pre><code>## x
##       0       1       2       3       4       5       6       7       8 
##      34     676    5890   31340  116732  327642  707973 1213672 1670133 
##       9      10      11      12      13      14      15      16      17 
## 1854021 1670069 1212136  708438  326233  117086   31280    5923     688 
##      18 
##      34</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">proptab.x &lt;-<span class="st"> </span>(<span class="kw">table</span>(x)/n); proptab.x</code></pre></div>
<pre><code>## x
##         0         1         2         3         4         5         6 
## 0.0000034 0.0000676 0.0005890 0.0031340 0.0116732 0.0327642 0.0707973 
##         7         8         9        10        11        12        13 
## 0.1213672 0.1670133 0.1854021 0.1670069 0.1212136 0.0708438 0.0326233 
##        14        15        16        17        18 
## 0.0117086 0.0031280 0.0005923 0.0000688 0.0000034</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(proptab.x[<span class="dv">8</span>:<span class="dv">19</span>])</code></pre></div>
<pre><code>## [1] 0.8809713</code></pre>
<p>If <span class="math inline">\(H_0\)</span> were true we would see 7 or more correct picks in a sample of 18, by chance alone, with a <span class="math inline">\(P-value\)</span> of <code>0.8809713</code>. Since this is <span class="math inline">\(&gt; 0.05\)</span> we fail to reject <span class="math inline">\(H_0\)</span>. That is, the data provide insufficient evidence to conclude that subjects pick the mother at most half the time (i.e., that sons resemble their mothers).</p>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
